// Code generated by colgen v0.1.3; DO NOT EDIT.
package rest

import (
	"github.com/ssokov/pr-reviewer-service/internal/pr"
)

func NewPullRequestShorts(in []pr.PullRequest) []PullRequestShort {
	return Map(in, NewPullRequestShort)
}

func NewTeamMembers(in []pr.User) []TeamMember { return Map(in, NewTeamMember) }
