// Code generated by colgen v0.1.3; DO NOT EDIT.
package pr

import (
	"github.com/ssokov/pr-reviewer-service/internal/db"
)

func NewPullRequests(in []db.PullRequest) []PullRequest { return MapP(in, NewPullRequest) }

func NewReviewerStatsList(in []db.ReviewerStats) []ReviewerStats { return Map(in, NewReviewerStats) }

func NewTeams(in []db.Team) []Team { return MapP(in, NewTeam) }

func NewUsers(in []db.User) []User { return MapP(in, NewUser) }
